name: Tests

on:
  push:
    branches-ignore:
      - master

jobs:
  tests:
    name: E2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node_version: '18'
      - name: Run tests
        uses: cypress-io/github-action@v6
        env:
          TEST_REPORTER: 'junit'
          TEST_REPORTER_OPTIONS: '{"mochaFile": "test/results/test-output-[hash].xml"}'
        with:
          command: npm run test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: run-video
          path: test/videos
          retention-days: 2



